services:
  db:
    image: postgres:13.18
    restart: always
    container_name: its_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: 'vhost'
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  rabbitmq_data:
