services:
  db:
    image: postgres:13.18
    restart: always
    container_name: its_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: bitnami/rabbitmq:3.8.5
    container_name: its_rabbitmq
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: root
    ports:
      - "15672:15672"
      - "5672:5672"
