services:
  db:
    image: postgres:13.18
    restart: always
    container_name: its_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: 'vhost'
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - 'rabbitmq_data:/data'

#  prometheus:
#    image: prom/prometheus:v2.46.0
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus/tmp:/prometheus
#      - ./prometheus/config:/etc/prometheus
#    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
#
#  grafana:
#    image: grafana/grafana:10.0.3
#    ports:
#      - 3000:3000
#    volumes:
#      - ./grafana/tmp:/var/lib/grafana
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
#
#  alertmanager:
#    image: prom/alertmanager:v0.25.0
#    ports:
#      - "9093:9093"
#    volumes:
#      - ./alert-manager/tmp:/data
#      - ./alert-manager/config:/config
#    command: --config.file=/config/alertmanager.yml --log.level=debug

volumes:
  rabbitmq_data:
