### Info endpoint configuration
info:
  app:
    version: 1.0
    name: Issue Tracking System
    java:
      version: 21 Liberica
    description: Program typu issue tracker

### API prefixes
rest:
  prefix: /api
  public:
    path: /public
  secured:
    path: /secured

spring:
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  jackson:
    default-property-inclusion: non_null
  ### JPA open-in-view
  jpa:
    open-in-view: false
  ### LiquiBase properties
  liquibase:
    contexts: main
    change-log: classpath:db/changelog/liquibase-changelog.xml
