application:
  base-url: http://localhost:3000

email:
  messages:
    enabled: false

### Data source config (test)
spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5435/issue_tracker
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  ### Email sender config (dev)
  mail:
    host: <host>
    username: <username>
    password: <pass>
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass
    virtual-host: vhost


### JWT config
jwt:
  base64-secret: >-
    WCMjWk5YVitaIXJjUCwmLGQ/dkNJJTd3eEZKaTliVHQ4XixyJEJ+fk5hLGJ4dmVsfkFLc1MxWF5xZT9SZ2Z0ZGNmY2dmNDc0NjV2dGRmZmRnZmQ1NzY1N2ZoZmhnNjg3Ng
  expiration-in-seconds: '86400'

### event sourcing properties
event-sourcing:
  snapshotting:
    ISSUE:
      enabled: true
      nth-event: 20
  subscriptions:
    polling-initial-delay: PT1S
    polling-interval: PT1S

### issue assignments
issues:
  assigment:
    polling-interval: PT2M
    polling-initial-delay: PT2M

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: TRACE
